### PR TITLE
Add example usage to istanbul-lib-report

### PR DESCRIPTION
**Pull request by lukeapage**

### CODE REVIEW

File: packages/istanbul-lib-report/README.md [hunk 1]
```diff
@@ -3,4 +3,23 @@
 [![Greenkeeper badge](https://badges.greenkeeper.io/istanbuljs/istanbul-lib-report.svg)](https://greenkeeper.io/)
 [![Build Status](https://travis-ci.org/istanbuljs/istanbul-lib-report.svg?branch=master)](https://travis-ci.org/istanbuljs/istanbul-lib-report)
 
-Core reporting utilities for istanbul. Docs to follow.
+Core reporting utilities for istanbul.
+
+## example usage
```
Comment (coreyfarrell) [inline packages/istanbul-lib-report/README.md]: Prefer `## Example Usage` title case for this

File: packages/istanbul-lib-report/README.md [hunk 2]
```diff
@@ -3,4 +3,23 @@
...
+
+```
```
Comment (coreyfarrell) [inline packages/istanbul-lib-report/README.md]: Please use the `js` tag for this code block so we get syntax highlighting.

File: packages/istanbul-lib-report/README.md [hunk 3]
```diff
@@ -3,4 +3,23 @@
...
+const libReport = require('istanbul-lib-report');
+
+const context = libReport.createContext({
+  dir: 'source/dir',
```
Comment (coreyfarrell) [inline packages/istanbul-lib-report/README.md]: This isn't the source dir, it's the report output directory.

**Comment by coreyfarrell** [comment]
> Maybe another source for good examples would be jest's codebase, for inspiration

jest is currently not a good place to look.  jest is using the current version of istanbul modules.  index.js on istanbuljs/nyc#1134 is probably the only code that is using the `next` version of istanbul-lib-report.

**Comment by lukeapage** [comment]
Fixed comments. I'm not saying this is perfect - its just I tried the alpha and updated my codebase and I ended up using the example on the refactor pr description, so I did this as I went along and made a PR so that _something_ exists ;)

File: packages/istanbul-lib-report/README.md [hunk 4]
```diff
@@ -3,4 +3,28 @@
...
+## Example usage
+
+```js
+const libReport = require('istanbul-lib-report');
+const reports = require('istanbul-reports');
+
+// create a context for report generation
+const context = libReport.createContext({
+  dir: 'report/output/dir',
+  defaultSummarizer: 'summarizer name e.g. nested/flat/pkg',
```
Comment (JaKXz) [inline packages/istanbul-lib-report/README.md]: I think this should be a valid value, and have a comment describing what it is, so that people have an idea what they can copy/paste and then extend as necessary. I've been working a lot with Gatsby recently and their docs do a good job of this.

File: packages/istanbul-lib-report/README.md [hunk 5]
```diff
@@ -3,4 +3,28 @@
...
 [![Build Status](https://travis-ci.org/istanbuljs/istanbul-lib-report.svg?branch=master)](https://travis-ci.org/istanbuljs/istanbul-lib-report)
 
-Core reporting utilities for istanbul. Docs to follow.
+Core reporting utilities for istanbul.
+
+## Example usage
+
+```js
+const libReport = require('istanbul-lib-report');
+const reports = require('istanbul-reports');
```
Comment (JaKXz) [inline packages/istanbul-lib-report/README.md]: Could we destructure these imports? That makes reading examples like this [from other docs] clearer for me.

File: packages/istanbul-lib-report/README.md [hunk 6]
```diff
@@ -3,4 +3,28 @@
...
+// create a context for report generation
+const context = libReport.createContext({
+  dir: 'report/output/dir',
+  defaultSummarizer: 'summarizer name e.g. nested/flat/pkg',
+  watermarks: configWatermarks,
+  coverageMap,
+})
+
+// create an instance of the relevant report class
+const report = reports.create('report/name e.g. json/html/html-spa/text', {
```
Comment (JaKXz) [inline packages/istanbul-lib-report/README.md]: same as the `defaultSummarizer` comment.

File: packages/istanbul-lib-report/README.md [hunk 7]
```diff
@@ -3,4 +3,28 @@
...
+```js
+const libReport = require('istanbul-lib-report');
+const reports = require('istanbul-reports');
+
+// create a context for report generation
+const context = libReport.createContext({
+  dir: 'report/output/dir',
+  defaultSummarizer: 'summarizer name e.g. nested/flat/pkg',
+  watermarks: configWatermarks,
+  coverageMap,
```
Comment (JaKXz) [inline packages/istanbul-lib-report/README.md]: Variables like these last 2 I would like to see defined, so that devs know what needs to be passed here or how to get the coverageMap to this point.

File: packages/istanbul-lib-report/README.md (hunk 5 above)
Comment (lukeapage) [reply packages/istanbul-lib-report/README.md]: since the used variables are "create" and "createContext" and therefore to be clear the imports would need to be renamed, I feel like destructuring in this case makes the code less readable.

File: packages/istanbul-lib-report/README.md (hunk 7 above)
Comment (lukeapage) [reply packages/istanbul-lib-report/README.md]: I defined configWatermarks.
For coverageMap - its a ball of string.. I could include libCoverage and create a coverage map.. but that requires either passing an empty report or loading a report and merging it in.. where does it end? this is not at the top level - how to use all istanbul packages, this is how to use istanbul-reports. As the main readme states, most end users won't need this (though I am writing these docs because I partly disagree and think the main readme documentation is way to aggressive and unhelpful)

Comment (lukeapage) [reply packages/istanbul-lib-report/README.md]: I defined it with a comment.

**Comment by coreyfarrell** [comment]
@lukeapage thanks for contributing!

**Comment by Hypnosphi** [comment]
Doesn't seem to work with `istanbul-lib-report@2.0.8` and  `istanbul-reports@2.2.6`:

```
TypeError: reports.create(...).execute is not a function
```

**Comment by coreyfarrell** [comment]
@Hypnosphi that is true, these docs are for the 3.x versions (currently pre-release).
